[package]
name = "damascus"
version = "0.1.0"
authors = ["Owen Bulka <obulka@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.0"
futures = "0.3.4"
rayon = "1.1"
tokio = { version = "0.2", features = ["full"] }
specs = "0.15.1"
specs-hierarchy = "0.5.1"
wgpu = "0.5.0"
image = "0.22"
winit = "0.20.0-alpha3"
glsl-to-spirv = "0.1"
cgmath = "0.17"
failure = "0.1"
bytemuck = "1.2.0"