[package]
name = "damascus_ui"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
damascus_core = { path = "../damascus_core" }
anyhow = "1.0"
eframe = "0.19.0"
egui_node_graph = "0.4.0"
glam = "0.24"
serde = { version = "1.0", optional = true }
bytemuck = { version = "1.7.1", optional = true }
num = "0.4"
num-derive = "0.4"
num-traits = "0.2"

[features]
default = ["wgpu"]
persistence = ["serde", "egui_node_graph/persistence", "eframe/persistence"]
wgpu = ["eframe/wgpu", "bytemuck"]
