[package]
name = "damascus_ui"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
damascus_core = { path = "../damascus_core" }
anyhow = "1.0"
eframe = { version = "0.19", features = ["persistence", "wgpu"]}
egui_node_graph = { version = "0.4.0", features = ["persistence"]}
glam = { version = "0.24", features = ["serde"] }
indoc = "2"
serde = "1.0"
serde_yaml = "0.9"
bytemuck = "1.7.1"
ndarray = { version = "0.15.6", features = ["serde"] }
rfd = "0.12"
strum = { version = "0.25", features = ["derive"] }
#undo_2 = "0.1" # one day...

[profile.release]
lto = true
